import Head from "next/head";
import Form from 'next/form'
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/router";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const [selectedFile, setSelectedFile] = useState<Blob>();
  useEffect(() => {
    fetch("http://localhost:3001/")
      .then((res) => {
        console.log(res)
        return res.text()
      })
      .then((res) => { console.log(res)})
  }, [])

  const router = useRouter()

  const submitForm = (event: FormEvent) => {
    if (typeof selectedFile === 'undefined') {
      alert("File Upload Error")
      return
    } 
    event.preventDefault()
    const formData = new FormData();
    formData.append("file", selectedFile);
  
    fetch('http://localhost:3001/upload-csv', { method: "POST", body: formData })
      .then((res) => res.json())
      .then((res) => { 
        router.push(`/${res.csvId}`)
      })
      .catch(() => alert("File Upload Error"));
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <h1>View and Search your CSV files here</h1>
          <Form action="/upload" onSubmit={submitForm}>
            <input name='csv' type='file' onChange={(e) => setSelectedFile(e.target?.files?.[0])}/>
            <button type="submit">Submit</button>
          </Form>
          <div className={styles.ctas}>
          </div>
        </main>
        <footer className={styles.footer}>
        </footer>
      </div>
    </>
  );
}
